-- Zero-row diagnostic: returns one row per migrated table whose source and
-- target row counts DON'T match. A healthy migration produces an empty result.
-- Source and target counts both come from reconciliation_report.json,
-- generated by validation/validator.py and loaded here as a seed.
-- The singular test tests/assert_row_counts_match.sql fails dbt when this
-- model returns any rows.
SELECT
    table_name,
    source_row_count,
    target_row_count,
    source_row_count - target_row_count AS row_delta
FROM {{ ref('migration_counts_seed') }}
WHERE source_row_count != target_row_count
