-- Compares source vs target row counts per migrated table.
-- Source and target counts both come from reconciliation_report.json,
-- generated by validation/validator.py and loaded here as a seed
-- (target counts are also queryable live from Snowflake, but reusing
-- the reconciliation report keeps this model consistent with the
-- report that the audit trail already references).
SELECT
    table_name,
    source_row_count,
    target_row_count,
    source_row_count - target_row_count AS row_delta,
    CASE WHEN source_row_count = target_row_count THEN 'PASS' ELSE 'FAIL' END AS status
FROM {{ ref('migration_counts_seed') }}
